collector_name: remnawave_node_metrics

metrics:
  - metric_name: remnawave_users_online
    type: gauge
    help: "Number of online users on the node"
    key_labels:
      - uuid
      - name
      - country_code
    values: [ users_online ]
    query_ref: remnawave_users_online
  - metric_name: remnawave_xray_version
    type: gauge
    help: "XRay version on the node"
    key_labels:
      - uuid
      - name
      - version
    values: [ xray_version ]
    query_ref: remnawave_xray_version
  - metric_name: remnawave_xray_uptime
    type: gauge
    help: "XRay uptime on the node"
    key_labels:
      - uuid
      - name
    values: [ xray_uptime ]
    query_ref: remnawave_xray_uptime

queries:
  - query_name: remnawave_users_online
    query: |
      SELECT uuid, name, country_code, users_online FROM nodes;
  - query_name: remnawave_xray_version
    query: |
      SELECT uuid, name, xray_version AS version,
      (
        split_part(xray_version, '.', 1)::int * 100 +
        split_part(xray_version, '.', 2)::int * 10 +
        split_part(xray_version, '.', 3)::int
      ) AS xray_version
      FROM nodes;
  - query_name: remnawave_xray_uptime
    query: |
      SELECT uuid, name, xray_uptime FROM nodes;
